version: '3'

networks:
  default:
    external:
      name: prodnetwork

services:
  shellinabox:
    image: sspreitzer/shellinabox
    container_name: shellinabox
    restart: always
    expose:
      - "4200"
    environment:
      - SIAB_USER=user 
      - SIAB_PASSWORD=password
      - SIAB_SSL=false
      - VIRTUAL_HOST=example.com 
      - VIRTUAL_PORT=4200
